### PR TITLE
Add secp256r1 to CurveType

### PR DESCRIPTION
**Pull request by joeqian10**
### Motivation

NEO uses P256.

### CODE REVIEW

**Comment by joeqian10** [comment]
@patrick-ogrady Hi Patrick, can you explain more about what I need to do to pass `check-gen`. I spent half hour on this and still got no ideas, since this is new stuff for me. Thanks!

**Comment by patrick-ogrady** [comment]
What error are you getting @joeqian10? Have you run `make deps`? What version of node are you running?

**Comment by joeqian10** [comment]
@patrick-ogrady 
image

**Comment by patrick-ogrady** [comment]
@joeqian10 looks like the latest commit (that fixed the issue) wasn't signed...you'll need to do so before I can merge this!

**Comment by joeqian10** [comment]
@patrick-ogrady Thank you so much for all the guidance and help!

**Pull request merged**
